"""Golden-vector tests for the NWC coincurve crypto (ported from the LE MCP).

Ported from ``lightning-enable-mcp/tests/test_nwc_coincurve_vectors.py`` and
adapted to l402-requests' module API. These pin the curve operations in
``nwc.py`` against INDEPENDENT ground truth, so a green run proves coincurve
produces byte-correct output — not merely that it's self-consistent:

  1. Pubkey derivation  -> the canonical BIP340 test vector (seckey 3).
  2. Raw shared-X ECDH  -> cross-checked against ``cryptography``'s SECP256K1
                           ECDH (a second, unrelated implementation) AND symmetry.
  3. Schnorr sign/verify -> round-trips through the production verify gate, and a
                           one-bit-flipped signature is rejected (the F-11 gate).
  4. NIP-04 encrypt/decrypt -> raw-shared-X wire format round-trips.
"""

import hashlib
import hmac
import time
from unittest.mock import patch

from l402_requests.wallets.nwc import (
    NwcWallet,
    _compute_nostr_event_id,
    _compute_shared_x,
    _derive_xonly_pubkey,
    _nip04_decrypt,
    _nip04_encrypt,
    _nip44_decrypt,
    _nip44_encrypt,
    verify_nostr_event_signature,
)

# --- BIP340 canonical vector: secret scalar 3 -> known x-only pubkey ----------
SECKEY_3 = (3).to_bytes(32, "big")
BIP340_PUBKEY_X_FOR_3 = (
    "f9308a019258c31049344f85f89d5229b531c845836f99b08601f113bce036f9"
)

# A second deterministic, valid scalar for ECDH tests.
SECKEY_A = b"\x01" + b"\x42" * 31


def _crypto_ecdh_shared_x(priv_bytes: bytes, pub_x_hex: str) -> bytes:
    """Independent raw shared-X via ``cryptography``'s SECP256K1 ECDH.

    Reconstructs the peer point as 02||X (even-Y) — the same convention the
    production code uses — and returns the X coordinate of priv*peer.
    """
    from cryptography.hazmat.primitives.asymmetric import ec

    priv = ec.derive_private_key(int.from_bytes(priv_bytes, "big"), ec.SECP256K1())
    comp = bytes.fromhex("02" + pub_x_hex)
    peer = ec.EllipticCurvePublicKey.from_encoded_point(ec.SECP256K1(), comp)
    # exchange() returns the shared point's X coordinate, big-endian 32 bytes.
    return priv.exchange(ec.ECDH(), peer)


def test_derive_xonly_pubkey_matches_bip340_vector():
    assert _derive_xonly_pubkey(SECKEY_3) == BIP340_PUBKEY_X_FOR_3


def test_compute_shared_x_matches_independent_cryptography_ecdh():
    # priv = A, peer = BIP340 vector pubkey (even-Y x-only).
    got = _compute_shared_x(SECKEY_A, BIP340_PUBKEY_X_FOR_3)
    expected = _crypto_ecdh_shared_x(SECKEY_A, BIP340_PUBKEY_X_FOR_3)
    assert got == expected, (
        "raw shared-X must match an independent ECDH impl (CoinOS path)"
    )
    assert len(got) == 32


def test_compute_shared_x_is_symmetric():
    # ECDH(a, B) and ECDH(b, A) yield the same shared-X (even-Y convention both).
    # This is exactly what makes the client<->wallet NWC crypto interoperate.
    a_pub = _derive_xonly_pubkey(SECKEY_A)
    b_pub = BIP340_PUBKEY_X_FOR_3
    ab = _compute_shared_x(SECKEY_A, b_pub)
    ba = _compute_shared_x(SECKEY_3, a_pub)
    assert ab == ba


def _build_signed_event(secret_key: bytes, pubkey_hex: str, content: str) -> dict:
    event = {
        "kind": 13194,
        "pubkey": pubkey_hex,
        "created_at": int(time.time()),
        "tags": [["encryption", "nip04 nip44_v2"]],
        "content": content,
    }
    event["id"] = _compute_nostr_event_id(event)
    event["sig"] = NwcWallet._sign_event(secret_key, event["id"])
    return event


def test_sign_then_verify_round_trip():
    pub = _derive_xonly_pubkey(SECKEY_3)
    event = _build_signed_event(SECKEY_3, pub, "hello world")
    assert verify_nostr_event_signature(event, pub) is True


def test_one_bit_flipped_signature_is_rejected():
    pub = _derive_xonly_pubkey(SECKEY_3)
    event = _build_signed_event(SECKEY_3, pub, "hello world")
    # Flip the last nibble of the signature — a valid-length but wrong sig.
    sig = event["sig"]
    flipped = sig[:-1] + ("0" if sig[-1] != "0" else "1")
    event["sig"] = flipped
    assert verify_nostr_event_signature(event, pub) is False


def test_nip04_encrypt_decrypt_round_trip():
    # Alice encrypts to Bob; Bob decrypts with his secret + Alice's pubkey.
    alice_sec = SECKEY_A
    alice_pub = _derive_xonly_pubkey(alice_sec)
    bob_sec = SECKEY_3
    bob_pub = _derive_xonly_pubkey(bob_sec)

    ciphertext = _nip04_encrypt(
        alice_sec, bob_pub, "the magic words are squeamish ossifrage"
    )
    assert "?iv=" in ciphertext
    plaintext = _nip04_decrypt(bob_sec, alice_pub, ciphertext)
    assert plaintext == "the magic words are squeamish ossifrage"


# ── Fixed-IV / fixed-nonce KNOWN-ANSWER vectors (ported from l402-ts) ─────────
#
# Ported verbatim from l402-ts/tests/wallets/nwc-crypto.test.ts. These payloads
# were GENERATED by the proven MCP Python NWC client (coincurve + cryptography)
# with the fixed SHARED_X / IV / nonce below, then hardcoded. Unlike a random-
# nonce round-trip (which would pass even a wrong-but-symmetric impl with swapped
# nonce/hmac slices or a wrong HKDF salt/info), a byte-for-byte KAT pins the exact
# wire format: encrypting with the fixed IV/nonce MUST reproduce these exact bytes,
# and decrypting these exact payloads MUST yield the known plaintext.
#
# The vectors are keyed on a fixed shared-X, so we patch ``_compute_shared_x``
# (bypassing ECDH) and ``os.urandom`` (to inject the fixed IV / nonce).
_KAT_SHARED_X = "150b9a865720b12157e2f5463189a5da551586e655bb4babba40e05594005551"
_KAT_CONVERSATION_KEY = (
    "e0f6f2aeb0e50f479fd0da0e7b6965799a0104754d6448f4a7332138add9914d"
)
_KAT_IV16 = "000102030405060708090a0b0c0d0e0f"
_KAT_NONCE32 = "000102030405060708090a0b0c0d0e0f101112131415161718191a1b1c1d1e1f"
_KAT_PLAINTEXT = "the magic words are squeamish ossifrage"
_KAT_NIP04_CIPHERTEXT = (
    "6m20/hddxV4krD0M7AllC54Eptvx7tvPyR4X5eatqLooNc+icAf9etlMrqjsuxBB"
    "?iv=AAECAwQFBgcICQoLDA0ODw=="
)
_KAT_NIP44_PAYLOAD = (
    "AgABAgMEBQYHCAkKCwwNDg8QERITFBUWFxgZGhscHR4fT/aulO+u59qN09JORRy56fr0mp6XbC+"
    "D+xeTWCfjbmL1iG+Esy/F/+oQuwD4Dmds+vvyR23i3tN79c2FoAI7Ob1mpWi2sjzpkrSBzADQ8P"
    "KnlmKJFJfV1KbZcrUP4+LMMXY="
)
_KAT_NIP44_SHORT_PAYLOAD = (
    "AgABAgMEBQYHCAkKCwwNDg8QERITFBUWFxgZGhscHR4fT9C7/IqOirvqurFuMnPLjYnU++zyTFzy"
    "jnLyNU6QBkKa++S8f+jhv2DY4r7VJUDJ3CeMnxD/M6YP8wmYCmGiFZ5v"
)

_KAT_DUMMY_SECRET = b"\x01" * 32
_KAT_DUMMY_PUBKEY = "02" + "ab" * 32  # unused — ECDH is patched out
_PATCH_SHARED_X = "l402_requests.wallets.nwc._compute_shared_x"


def _fixed_urandom(n: int) -> bytes:
    """Deterministic os.urandom: fixed IV for NIP-04 (16), fixed nonce for NIP-44 (32)."""
    if n == 16:
        return bytes.fromhex(_KAT_IV16)
    if n == 32:
        return bytes.fromhex(_KAT_NONCE32)
    return b"\x00" * n


def test_kat_conversation_key_salt_and_derivation():
    # HKDF-extract(salt="nip44-v2", ikm=shared_x) == HMAC-SHA256("nip44-v2", shared_x).
    # Pins the salt used by _nip44_encrypt/_decrypt against the l402-ts vector.
    ck = hmac.new(
        b"nip44-v2", bytes.fromhex(_KAT_SHARED_X), hashlib.sha256
    ).hexdigest()
    assert ck == _KAT_CONVERSATION_KEY


@patch("os.urandom", _fixed_urandom)
@patch(_PATCH_SHARED_X, return_value=bytes.fromhex(_KAT_SHARED_X))
def test_kat_nip04_encrypt_fixed_iv_reproduces_exact_bytes(_mock_sx):
    got = _nip04_encrypt(_KAT_DUMMY_SECRET, _KAT_DUMMY_PUBKEY, _KAT_PLAINTEXT)
    assert got == _KAT_NIP04_CIPHERTEXT


@patch(_PATCH_SHARED_X, return_value=bytes.fromhex(_KAT_SHARED_X))
def test_kat_nip04_decrypt_known_payload(_mock_sx):
    got = _nip04_decrypt(_KAT_DUMMY_SECRET, _KAT_DUMMY_PUBKEY, _KAT_NIP04_CIPHERTEXT)
    assert got == _KAT_PLAINTEXT


@patch("os.urandom", _fixed_urandom)
@patch(_PATCH_SHARED_X, return_value=bytes.fromhex(_KAT_SHARED_X))
def test_kat_nip44_encrypt_fixed_nonce_reproduces_exact_bytes(_mock_sx):
    got = _nip44_encrypt(_KAT_DUMMY_SECRET, _KAT_DUMMY_PUBKEY, _KAT_PLAINTEXT)
    assert got == _KAT_NIP44_PAYLOAD


@patch(_PATCH_SHARED_X, return_value=bytes.fromhex(_KAT_SHARED_X))
def test_kat_nip44_decrypt_known_payload(_mock_sx):
    got = _nip44_decrypt(_KAT_DUMMY_SECRET, _KAT_DUMMY_PUBKEY, _KAT_NIP44_PAYLOAD)
    assert got == _KAT_PLAINTEXT


@patch("os.urandom", _fixed_urandom)
@patch(_PATCH_SHARED_X, return_value=bytes.fromhex(_KAT_SHARED_X))
def test_kat_nip44_short_single_char_padded_to_32(_mock_sx):
    # 1-char plaintext padded to 32 bytes — exercises the padding bucket boundary.
    assert _nip44_decrypt(_KAT_DUMMY_SECRET, _KAT_DUMMY_PUBKEY, _KAT_NIP44_SHORT_PAYLOAD) == "a"
    assert _nip44_encrypt(_KAT_DUMMY_SECRET, _KAT_DUMMY_PUBKEY, "a") == _KAT_NIP44_SHORT_PAYLOAD
